# SPDX-FileCopyrightText: 2026 Giovanni MARIANO
#
# SPDX-License-Identifier: MPL-2.0

from typing import Any, Sequence

__version__: str

class System:
    def __init__(self) -> None: ...
    @property
    def cell_count(self) -> int: ...
    @property
    def surface_count(self) -> int: ...
    @property
    def universe_count(self) -> int: ...
    @property
    def volume_path_count(self) -> int: ...
    def clone(self) -> System: ...
    def get_cell_by_index(self, index: int) -> dict[str, Any]: ...
    def cell_find(self, cell_id: int) -> int | None: ...
    def surface_find(self, surface_id: int) -> int | None: ...
    def surface_id_at(self, index: int) -> int: ...
    def cell_set_region(self, cell_index: int, region_node: int) -> None: ...
    def cell_remove(self, cell_index: int) -> None: ...
    def find_all_cells_coverage(
        self, x: float, y: float, z: float, max_hits: int = 256,
        universe_id: int = 0, universe_depth: int = -1,
    ) -> dict[str, Any]: ...
    def point_inside(self, node_id: int, x: float, y: float, z: float) -> bool: ...
    def add_transform(
        self, transform_id: int, values: Sequence[float], degrees: bool = False
    ) -> int: ...
    def add_inline_transform(
        self, values: Sequence[float], degrees: bool = False,
        cell_id: int = 0, role: str | None = "fill"
    ) -> int: ...
    def set_fill(
        self, cell_index: int, fill_universe: int, transform: int = 0
    ) -> None: ...
    def rhp_surface(
        self, surface_id: int, base_x: float, base_y: float, base_z: float,
        height_x: float, height_y: float, height_z: float,
        r1_x: float, r1_y: float, r1_z: float,
        r2_x: float, r2_y: float, r2_z: float,
        r3_x: float, r3_y: float, r3_z: float,
    ) -> tuple[int, int, int]: ...
    def surface_set_boundary(self, surface_id: int, boundary: str) -> None: ...
    def surface_get_boundary(self, surface_id: int) -> str: ...
    def export_mcnp(self, filename: str, deduplicate: bool = True,
                    universe_depth: int = -1, fill_depth: int = 0) -> None: ...
    def export_mcnp_string(self, deduplicate: bool = True,
                           universe_depth: int = -1,
                           fill_depth: int = 0) -> str: ...
    def export_openmc(self, filename: str) -> None: ...
    def export_openmc_string(self) -> str: ...
    def export_serpent(self, filename: str) -> None: ...
    def export_serpent_string(self) -> str: ...
    def build_universe_index(self) -> None: ...
    def prepare_query_acceleration(self) -> None: ...
    def render_3d(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def validate_ray_slice_compact(
        self, *args: Any, **kwargs: Any
    ) -> dict[str, Any]: ...
    def slice_error_page(
        self, origin: Sequence[float], normal: Sequence[float],
        up: Sequence[float], view_bounds: Sequence[float],
        required_bounds: Sequence[float], tile_columns: int = 1,
        tile_rows: int = 1, page_index: int = 0,
        options: dict[str, Any] | None = None,
        max_index_bytes: int = 0,
    ) -> dict[str, Any]: ...
    def slice_error_query(
        self, origin: Sequence[float], normal: Sequence[float],
        up: Sequence[float], view_bounds: Sequence[float],
        required_bounds: Sequence[float], tile_columns: int = 1,
        tile_rows: int = 1, options: dict[str, Any] | None = None,
        max_index_bytes: int = 0,
    ) -> SliceErrorQuery: ...
    def __getattr__(self, name: str) -> Any: ...

class SliceErrorQuery:
    @property
    def page_count(self) -> int: ...
    def run_page(self, index: int) -> dict[str, Any]: ...
    def run_pages(
        self, indices: Sequence[int], workers: int = 0,
        max_parallel_scratch_bytes: int = 0,
    ) -> dict[str, Any]: ...
    def close(self) -> None: ...
    def __enter__(self) -> SliceErrorQuery: ...
    def __exit__(self, exc_type: Any, exc_value: Any,
                 traceback: Any) -> None: ...

class VoidResult:
    def __getattr__(self, name: str) -> Any: ...

class XsDir:
    def __init__(self, path: str, directory: bool = False) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Nuclide:
    def __init__(self, xsdir: XsDir, zaid: str, cached: bool = True) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ThermalScattering:
    def __init__(self, xsdir: XsDir, zaid: str) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class NucMaterial:
    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Multigroup:
    def __init__(self, bounds: Sequence[float]) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Source:
    def __init__(self, config: dict[str, Any]) -> None: ...
    integrated_emissivity: float | None

def sample_source(source: Source | dict[str, Any], histories: int = 1,
                  seed: int = 1, history_offset: int = 0) -> dict[str, Any]: ...

class ClusterContext:
    def __getattr__(self, name: str) -> Any: ...

def load_mcnp(filename: str) -> System: ...
def load_mcnp_string(input: str) -> System: ...
def load_openmc(filename: str) -> System: ...
def load_openmc_string(input: str) -> System: ...
def transport_run(system: System, xsdir: XsDir, config: dict[str, Any]) -> dict[str, Any]: ...
def generate_void(system: System, bounds: Any = None, max_depth: int = 8,
                  min_size: float = 0.1, probes_per_axis: int = 3,
                  bounds_region: Any = None, workers: int = 0,
                  max_parallel_scratch_bytes: int = 67_108_864) -> VoidResult: ...
def version() -> str: ...
def parallel_max_threads() -> int: ...
def set_parallel_threads(threads: int) -> int: ...
def get_error() -> str | None: ...
def clear_error() -> None: ...
def primitive_evaluate(
    primitive_type: int, parameters: Sequence[float], point: Sequence[float]
) -> float: ...
def set_log_level(level: int) -> None: ...
def get_log_level() -> int: ...
def enable_logging() -> None: ...
def disable_logging() -> None: ...
def parse_zaid(zaid: str) -> dict[str, Any]: ...
def reaction_classify(mt: int) -> str: ...
def cluster_initialize() -> None: ...
def cluster_finalize() -> None: ...
def cluster_create(communicator: int | None) -> ClusterContext: ...

NODE_INVALID: int
MATERIAL_NONE: int
PARALLEL_BACKEND: str
PARALLEL_MAX_THREADS: int
VERSION_MAJOR: int
VERSION_MINOR: int
VERSION_PATCH: int
LOG_NONE: int
LOG_ERROR: int
LOG_WARN: int
LOG_INFO: int
LOG_DEBUG: int
LOG_TRACE: int
ALEA_OP_PRIMITIVE: int
ALEA_OP_UNION: int
ALEA_OP_INTERSECTION: int
ALEA_OP_DIFFERENCE: int
ALEA_OP_COMPLEMENT: int
PRIMITIVE_PLANE: int
PRIMITIVE_SPHERE: int
PRIMITIVE_CYLINDER_X: int
PRIMITIVE_CYLINDER_Y: int
PRIMITIVE_CYLINDER_Z: int
PRIMITIVE_CONE_X: int
PRIMITIVE_CONE_Y: int
PRIMITIVE_CONE_Z: int
PRIMITIVE_RPP: int
PRIMITIVE_QUADRIC: int
PRIMITIVE_TORUS_X: int
PRIMITIVE_TORUS_Y: int
PRIMITIVE_TORUS_Z: int
PRIMITIVE_RCC: int
PRIMITIVE_BOX: int
PRIMITIVE_SPH: int
PRIMITIVE_TRC: int
PRIMITIVE_ELL: int
PRIMITIVE_REC: int
PRIMITIVE_WED: int
PRIMITIVE_RHP: int
PRIMITIVE_ARB: int
