# SPDX-FileCopyrightText: 2026 Giovanni MARIANO
#
# SPDX-License-Identifier: MPL-2.0

import gc
import json
import weakref
from pathlib import Path

import numpy as np
import pytest

import pyalea


@pytest.fixture
def populated_system():
    system = pyalea.System()
    _, _, inside = system.sphere_surface(1, 0.0, 0.0, 0.0, 2.0)
    material = system.add_material(7)
    system.add_cell(101, inside, material, 1.0)
    system.build_universe_index()
    return system


def test_native_module_is_private_package_member():
    assert pyalea.System.__module__ == "pyalea._alea"
    assert pyalea.version().count(".") == 2
    assert pyalea.__version__ == pyalea.version()


def test_public_names_are_forwarded():
    assert "System" in pyalea.__all__
    assert pyalea.System is pyalea._alea.System
    assert "_alea" not in pyalea.__all__
    assert set(pyalea.__all__) == {
        name for name in dir(pyalea._alea) if not name.startswith("_")
    }


def test_rhp_constructor_accepts_documented_arity():
    system = pyalea.System()
    index, positive, negative = system.rhp_surface(
        17, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0,
        2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
    assert index == 0
    assert positive != negative


def test_surface_boundary_metadata_round_trip():
    system = pyalea.System()
    system.sphere_surface(1, 0.0, 0.0, 0.0, 2.0)
    system.surface_set_boundary(1, "reflective")
    assert system.surface_get_boundary(1) == "reflective"


@pytest.mark.parametrize(
    ("primitive_type", "parameters", "inside", "outside"),
    [
        (pyalea.PRIMITIVE_SPHERE, (0, 0, 0, 2), (0, 0, 0), (3, 0, 0)),
        (pyalea.PRIMITIVE_BOX,
         (0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4),
         (1, 1, 1), (3, 1, 1)),
        (pyalea.PRIMITIVE_REC,
         (0, 0, 0, 0, 0, 4, 2, 0, 0, 0, 1, 0),
         (0, 0, 2), (3, 0, 2)),
        (pyalea.PRIMITIVE_WED,
         (0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 4),
         (0.25, 0.25, 2), (2, 2, 2)),
        (pyalea.PRIMITIVE_RHP,
         (0, 0, 0, 0, 0, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0),
         (0, 0, 2), (3, 0, 2)),
    ],
)
def test_standalone_primitive_evaluation(
        primitive_type, parameters, inside, outside):
    assert pyalea.primitive_evaluate(primitive_type, parameters, inside) < 0
    assert pyalea.primitive_evaluate(primitive_type, parameters, outside) > 0


def test_standalone_primitive_evaluation_validates_inputs():
    with pytest.raises(ValueError, match="exactly 4"):
        pyalea.primitive_evaluate(pyalea.PRIMITIVE_SPHERE, (0, 0, 0), (0, 0, 0))
    with pytest.raises(ValueError, match="invalid or unsupported"):
        pyalea.primitive_evaluate(pyalea.PRIMITIVE_SPHERE, (0, 0, 0, 0), (0, 0, 0))
    with pytest.raises(ValueError, match="finite"):
        pyalea.primitive_evaluate(
            pyalea.PRIMITIVE_SPHERE, (0, 0, 0, 2), (float("nan"), 0, 0))


def test_parallel_runtime_value_stays_synchronized():
    original = pyalea.parallel_max_threads()
    try:
        assert pyalea.set_parallel_threads(2) == 2
        assert pyalea.PARALLEL_MAX_THREADS == 2
        assert pyalea._alea.PARALLEL_MAX_THREADS == 2
    finally:
        pyalea.set_parallel_threads(original)


def test_packaged_build_metadata_when_present():
    metadata_path = Path(pyalea.__file__).with_name("_build_info.json")
    if not metadata_path.exists():
        pytest.skip("build metadata is generated by the package target")
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    assert metadata["libalea_version"] == pyalea.version()
    assert len(metadata["libalea_commit"]) == 40
    assert set(metadata["libalea_commit"]) <= set("0123456789abcdef")
    assert Path(pyalea.__file__).with_name("__init__.pyi").is_file()
    assert Path(pyalea.__file__).with_name("py.typed").is_file()


def test_numpy_grid_arrays_have_stable_layout_and_dtypes(populated_system):
    grid = populated_system.find_cells_grid_z(
        0.0, -3.0, 3.0, -3.0, 3.0, 9, 7,
        error_mode="fast", _as_buffers=True,
    )

    expected = {
        "cell_ids": np.dtype(np.intc),
        "material_ids": np.dtype(np.intc),
        "secondary_cell_ids": np.dtype(np.intc),
        "coverage": np.dtype(np.uint8),
        "errors": np.dtype(np.uint8),
    }
    for name, dtype in expected.items():
        array = grid[name]
        assert isinstance(array, np.ndarray)
        assert array.dtype == dtype
        assert array.shape == (63,)
        assert array.flags.c_contiguous
        assert array.flags.writeable

    assert 101 in grid["cell_ids"]
    assert 7 in grid["material_ids"]


def test_numpy_arrays_own_native_storage_after_system_destruction(populated_system):
    grid = populated_system.find_cells_grid_z(
        0.0, -3.0, 3.0, -3.0, 3.0, 8, 6, _as_buffers=True,
    )
    cells = grid["cell_ids"]
    expected = cells.copy()
    assert cells.base is not None

    del grid
    del populated_system
    gc.collect()

    np.testing.assert_array_equal(cells, expected)
    cells[0] = 12345
    assert cells[0] == 12345


def test_numpy_grid_releases_all_arrays_with_result(populated_system):
    grid = populated_system.find_cells_grid_z(
        0.0, -3.0, 3.0, -3.0, 3.0, 8, 6,
        error_mode="fast", _as_buffers=True,
    )
    references = [weakref.ref(value) for value in grid.values()
                  if isinstance(value, np.ndarray)]
    assert references

    del grid
    gc.collect()

    assert all(reference() is None for reference in references)


def test_reinitializing_owned_types_replaces_native_state():
    system = pyalea.System()
    system.__init__()
    assert system.cell_count == 0

    material = pyalea.NucMaterial()
    material.__init__()

    multigroup = pyalea.Multigroup([10.0, 1.0, 0.1])
    multigroup.__init__([20.0, 2.0])
    assert multigroup.n_groups == 1


def transformed_fill_system(transform_factory):
    system = pyalea.System()
    _, _, sphere = system.sphere_surface(1, 0.0, 0.0, 0.0, 1.5)
    _, _, container_region = system.box_surface(
        2, -50.0, 50.0, -50.0, 50.0, -50.0, 50.0,
    )
    material = system.add_material(7)
    system.add_cell(10, sphere, material, -1.0, universe_id=1)
    container = system.add_cell(1, container_region)
    transform_id = transform_factory(system)
    system.set_fill(container, 1, transform_id)
    system.build_universe_index()
    return system, transform_id


def test_named_transform_positions_programmatic_fill():
    system, transform_id = transformed_fill_system(
        lambda system: system.add_transform(41, (10.0, 0.0, 0.0)),
    )

    assert transform_id == 41
    assert system.material_at(10.0, 0.0, 0.0) == 7

    assert system.add_transform(41, (-10.0, 0.0, 0.0)) == 41
    assert system.material_at(-10.0, 0.0, 0.0) == 7


def test_inline_transform_deduplicates_and_positions_programmatic_fill():
    def add_inline(system):
        first = system.add_inline_transform(
            (10.0, 0.0, 0.0), cell_id=1, role="fill",
        )
        duplicate = system.add_inline_transform(
            (10.0, 0.0, 0.0), cell_id=2, role="fill",
        )
        assert duplicate == first
        return first

    system, transform_id = transformed_fill_system(add_inline)

    assert transform_id > 0
    assert system.material_at(10.0, 0.0, 0.0) == 7


def test_transform_values_are_validated():
    system = pyalea.System()
    with pytest.raises(ValueError, match="between 3 and 13"):
        system.add_transform(1, (1.0, 2.0))
    with pytest.raises(ValueError, match="rotation"):
        system.add_inline_transform((0.0, 0.0, 0.0, 0.5))


def test_in_memory_exports(populated_system):
    mcnp = populated_system.export_mcnp_string()
    openmc = populated_system.export_openmc_string()
    serpent = populated_system.export_serpent_string()

    assert "Exported by CSG Library" in mcnp
    assert "<geometry>" in openmc
    assert "exported by Alea" in serpent


def test_compact_validation_reports_trace_reuse(populated_system):
    result = populated_system.validate_ray_slice_compact(
        (0.0, 0.0, 0.0),
        (0.0, 0.0, 1.0),
        (0.0, 1.0, 0.0),
        -3.0, 3.0, -3.0, 3.0, 8,
    )

    assert isinstance(result["executed_trace_mask"], int)
    assert isinstance(result["reused_trace_mask"], int)
    assert result["executed_trace_mask"] != 0


def test_numpy_buffers_survive_repeated_allocation_and_collection():
    retained = []
    for size in range(2, 10):
        system = pyalea.System()
        _, _, inside = system.sphere_surface(1, 0.0, 0.0, 0.0, 2.0)
        material = system.add_material(7)
        system.add_cell(101, inside, material, 1.0)
        system.build_universe_index()
        grid = system.find_cells_grid_z(
            0.0, -2.5, 2.5, -2.5, 2.5, size, size,
            _as_buffers=True,
        )
        materials = grid["material_ids"]
        retained.append((materials, materials.copy()))
        del grid
        del system
    gc.collect()

    for size, (array, expected) in zip(range(2, 10), retained):
        assert array.shape == (size * size,)
        np.testing.assert_array_equal(array, expected)


def test_numpy_grid_rejects_invalid_dimensions(populated_system):
    with pytest.raises(ValueError):
        populated_system.find_cells_grid_z(
            0.0, -1.0, 1.0, -1.0, 1.0, 0, 4,
            _as_buffers=True,
        )
