# SPDX-FileCopyrightText: 2026 Giovanni MARIANO
#
# SPDX-License-Identifier: MPL-2.0

import gc
import json
from pathlib import Path

import numpy as np
import pytest

import pyalea


@pytest.fixture
def populated_system():
    system = pyalea.System()
    _, _, inside = system.sphere_surface(1, 0.0, 0.0, 0.0, 2.0)
    material = system.add_material(7)
    system.add_cell(101, inside, material, 1.0)
    system.build_universe_index()
    return system


def test_native_module_is_private_package_member():
    assert pyalea.System.__module__ == "pyalea._alea"
    assert pyalea.version().count(".") == 2
    assert pyalea.__version__ == pyalea.version()


def test_public_names_are_forwarded():
    assert "System" in pyalea.__all__
    assert pyalea.System is pyalea._alea.System


def test_parallel_runtime_value_stays_synchronized():
    original = pyalea.parallel_max_threads()
    try:
        assert pyalea.set_parallel_threads(2) == 2
        assert pyalea.PARALLEL_MAX_THREADS == 2
        assert pyalea._alea.PARALLEL_MAX_THREADS == 2
    finally:
        pyalea.set_parallel_threads(original)


def test_packaged_build_metadata_when_present():
    metadata_path = Path(pyalea.__file__).with_name("_build_info.json")
    if not metadata_path.exists():
        pytest.skip("build metadata is generated by the package target")
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    assert metadata["libalea_version"] == pyalea.version()
    assert len(metadata["libalea_commit"]) == 40
    assert set(metadata["libalea_commit"]) <= set("0123456789abcdef")


def test_numpy_grid_arrays_have_stable_layout_and_dtypes(populated_system):
    grid = populated_system.find_cells_grid_z(
        0.0, -3.0, 3.0, -3.0, 3.0, 9, 7,
        error_mode="fast", _as_buffers=True,
    )

    expected = {
        "cell_ids": np.dtype(np.intc),
        "material_ids": np.dtype(np.intc),
        "secondary_cell_ids": np.dtype(np.intc),
        "coverage": np.dtype(np.uint8),
        "errors": np.dtype(np.uint8),
    }
    for name, dtype in expected.items():
        array = grid[name]
        assert isinstance(array, np.ndarray)
        assert array.dtype == dtype
        assert array.shape == (63,)
        assert array.flags.c_contiguous
        assert array.flags.writeable

    assert 101 in grid["cell_ids"]
    assert 7 in grid["material_ids"]


def test_numpy_arrays_own_native_storage_after_system_destruction(populated_system):
    grid = populated_system.find_cells_grid_z(
        0.0, -3.0, 3.0, -3.0, 3.0, 8, 6, _as_buffers=True,
    )
    cells = grid["cell_ids"]
    expected = cells.copy()
    assert cells.base is not None

    del grid
    del populated_system
    gc.collect()

    np.testing.assert_array_equal(cells, expected)
    cells[0] = 12345
    assert cells[0] == 12345


def test_numpy_buffers_survive_repeated_allocation_and_collection():
    retained = []
    for size in range(2, 10):
        system = pyalea.System()
        _, _, inside = system.sphere_surface(1, 0.0, 0.0, 0.0, 2.0)
        material = system.add_material(7)
        system.add_cell(101, inside, material, 1.0)
        system.build_universe_index()
        grid = system.find_cells_grid_z(
            0.0, -2.5, 2.5, -2.5, 2.5, size, size,
            _as_buffers=True,
        )
        materials = grid["material_ids"]
        retained.append((materials, materials.copy()))
        del grid
        del system
    gc.collect()

    for size, (array, expected) in zip(range(2, 10), retained):
        assert array.shape == (size * size,)
        np.testing.assert_array_equal(array, expected)


def test_numpy_grid_rejects_invalid_dimensions(populated_system):
    with pytest.raises(ValueError):
        populated_system.find_cells_grid_z(
            0.0, -1.0, 1.0, -1.0, 1.0, 0, 4,
            _as_buffers=True,
        )
